groups:
    - name: mudita_devs
      reviewers: 1
      usernames:
          - lukasznn1
          - MateuszMroz
    - name: miquido_devs
      reviewers: 1
      usernames:
          - aamq
          - romansavka-mq
